/*
 * Swagger Generator
 *
 * This is an online swagger codegen server.  You can find out more at https://github.com/swagger-api/swagger-codegen or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * API version: 3.0.14
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vmodels

// adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
type AuthorizationValue struct {
	// Authorization value
	Value string `json:"value,omitempty"`
	// Authorization key
	KeyName string `json:"keyName,omitempty"`
	// Authorization type
	Type_ string `json:"type,omitempty"`
}
