package helper

/**
 * TokitaDevEngine version {{generatorVersion}}
 * Generated by engine {{generatorClass}}
 * Generated on {{generateDate}}
 * Developed by sulaimanfahmi@gmail.com
 */
import (
	"regexp"
    "encoding/json"
)

func GetEnvironment(value string) string {
	regex := regexp.MustCompile(`^\$\{([^}^{]+)\}`)
	if regex.MatchString(value) {
		return string(value[2 : len(value)-1])
	}
	return ""
}

func JsonToObject(byte []byte, intr interface{}) error {
	if err := json.Unmarshal(byte, intr); err != nil {
		return err
	}
	return nil
}

func ObjectToBytes(value interface{}) ([]byte, error) {
	result, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	return result, nil
}
