package helper

/**
 * TokitaDevEngine version {{generatorVersion}}
 * Generated by engine {{generatorClass}}
 * Generated on {{generateDate}}
 * Developed by sulaimanfahmi@gmail.com
 */
import (
	"regexp"
)

func GetEnvironment(value string) string {
	regex := regexp.MustCompile(`^\$\{([^}^{]+)\}`)
	if regex.MatchString(value) {
		return string(value[2 : len(value)-1])
	}
	return ""
}
