package helper

/**
 * TokitaDevEngine version {{generatorVersion}}
 * Generated by engine {{generatorClass}}
 * Generated on {{generateDate}}
 * Developed by sulaimanfahmi@gmail.com
 */

type ResponseMessage struct {
	ResponseCode    string
	ResponseMessage string
	HttpCode        int
    LogMessage      string
}

var (
	BAD_REQUEST = ResponseMessage{
    		ResponseCode:    "FL00023",
    		ResponseMessage: "Invalid request %s",
    		HttpCode:        400,
    		LogMessage:      "",
    	}
    SUCCESS = ResponseMessage{
            ResponseCode:    "FL0001",
            ResponseMessage: "succcess",
            HttpCode:        200,
        }
)
