package helper

/**
 * TokitaDevEngine version {{generatorVersion}}
 * Generated by engine {{generatorClass}}
 * Generated on {{generateDate}}
 * Developed by sulaimanfahmi@gmail.com
 */

type ResponseMessage struct {
	ResponseCode    string
	ResponseMessage string
}

var (
	SUCCESS, BAD_REQUEST, UNPROCESIBLEENTITY *ResponseMessage
)

func init() {
	SUCCESS = &ResponseMessage{
		ResponseCode:    "SC0000",
		ResponseMessage: "SUCCESS",
	}

	BAD_REQUEST = &ResponseMessage{
		ResponseCode:    "SC1000",
		ResponseMessage: "BAD REQUEST",
	}

	UNPROCESIBLEENTITY = &ResponseMessage{
		ResponseCode:    "SC2000",
		ResponseMessage: "UNPROCESIBLE ENTITY",
	}
}
