package configurations
/**
 * TokitaDevEngine version {{generatorVersion}}
 * Generated by engine {{generatorClass}}
 * Generated on {{generateDate}}
 * Developed by sulaimanfahmi@gmail.com
 */
const(
	SERVER_PORT ="SERVER_PORT"
	DATABASE_HOST="DATABASE_HOST"
)
