/*
 * Swagger Generator
 *
 * This is an online swagger codegen server.  You can find out more at https://github.com/swagger-api/swagger-codegen or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * API version: 3.0.14
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vmodels

type GenerationRequest struct {
	// language to generate (required)
	Lang string `json:"lang"`
	// spec in json format. . Alternative to `specURL`
	Spec *interface{} `json:"spec,omitempty"`
	// URL of the spec in json format. Alternative to `spec`
	SpecURL string `json:"specURL,omitempty"`
	// type of the spec
	Type_ string `json:"type,omitempty"`
	// codegen version to use
	CodegenVersion string `json:"codegenVersion,omitempty"`

	Options *Options `json:"options,omitempty"`
}
