/*
 * Swagger Generator
 *
 * This is an online swagger codegen server.  You can find out more at https://github.com/swagger-api/swagger-codegen or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * API version: 3.0.14
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package vmodels

type CliOption struct {

	OptionName string `json:"optionName,omitempty"`

	Description string `json:"description,omitempty"`
	// Data type is based on the types supported by the JSON-Schema
	Type_ string `json:"type,omitempty"`

	Enum map[string]string `json:"enum,omitempty"`

	Default_ string `json:"default,omitempty"`
}
