/**
 * TokitaDevEngine version {{generatorVersion}}
 * Generated by engine {{generatorClass}}
 * Generated on {{generateDate}}
 * Developed by sulaimanfahmi@gmail.com
 */
const {v4: uuidv4} = require('uuid')
const middleware = {}

middleware.requestId = (req, res, next) => {
    if (req.headers['x-request-id'] === undefined) {
        req.headers['x-request-id'] = uuidv4()
    }
    res.set('X-Request-Id', req.headers['x-request-id'])
    next()
}

middleware.globalRequest = (req, res, next) => {
    console.log({
        endpoint: req.url,
        headers: req.headers
    })
    next()
    console.log({
        endpoint: req.url,
        headers: res.header()._header
    })
}

module.exports = middleware
