/**
 * TokitaDevEngine version {{generatorVersion}}
 * Generated by engine {{generatorClass}}
 * Generated on {{generateDate}}
 * Developed by sulaimanfahmi@gmail.com
 */

const dotEnv = require('dotenv')
const mongoose = require('mongoose')

module.exports.loadConfiguration = function (envPath) {
    dotEnv.config({
        path: envPath
    })
    this.environment = {
        host: process.env.HOST,
        port: process.env.PORT,
        database: {
            host: process.env.MONGO_HOST
        },
        redis: {
            host: process.env.REDIS_HOST
        },
        password_directory_host: process.env.PASSWORD_DIRECTORY_HOST,
        password_directory_credential: process.env.PASSWORD_DIRECTORY_HOST_SECRET,
        password_directory_client_name: process.env.PASSWORD_DIRECTORY_HOST_CLIENT_NAME
    }
    return this
}

module.exports.loadDatabase = function (config) {
    mongoose.connect(config.environment.database.host, {
            useNewUrlParser: true,
            poolSize: 4,
            useFindAndModify: false,
            useUnifiedTopology: true

        }
    )
        .then(db => {
            console.log('mongo connected')
        }).catch(err => console.log('Mongo connection error', err))
    return mongoose
}
